source "https://rubygems.org"

# Server
gem "rails", "~> 4.2"
# gem "rails-api", "~> 0.4" # Enable this if you want to use Rails API
gem "puma", "~> 3.2"

# Data storages and queue systems

# General
gem "lazier", "~> 4.2"
gem "jbuilder", "~> 2.4"
gem "jwt", "~> 1.5"
gem "mustache", "~> 1.0"

# Testing
group :test do
  gem "rspec-rails", "~> 3.4"
  gem "timecop", "~> 0.8"
  gem "database_cleaner", "~> 1.5"
  gem "simplecov", "~> 0.11"
  gem "factory_girl", "~> 4.5"
  gem "faker", "~> 1.6"
  gem "rubocop", "~> 0.39"
end
